name: build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig build -Dtarget=x86_64-linux-gnu
      - run: zig build -Dtarget=aarch64-linux-gnu
      - run: zig build -Dtarget=x86_64-macos.11.0.0
      - run: zig build -Dtarget=aarch64-macos.11.0.0
      - run: zig build -Dtarget=x86_64-windows.win7
      - run: zig build -Dtarget=aarch64-windows

      - run: zig build test

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig build "-Dtarget=x86_64-windows.win7" test

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig build "-Dtarget=aarch64-macos.11.0.0" test

