name: build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      # Test all compilation/cross-compilation targets.
      - run: zig build -Dtarget=x86_64-linux-gnu
      - run: zig build -Dtarget=aarch64-linux-gnu
      - run: zig build -Dtarget=x86_64-macos.11.0.0
      - run: zig build -Dtarget=aarch64-macos.11.0.0
      - run: zig build -Dtarget=x86_64-windows.win7
      - run: zig build -Dtarget=aarch64-windows

      # Run the tests.
      - run: zig build -Dtarget=x86_64-linux test

      # Run valgrind.
      - name: Install valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind
      - name: Run valgrind
        working-directory: zig-out/bin
        run: valgrind --leak-check=full --error-exitcode=1 --exit-on-first-error=no ./unit-tests

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig build "-Dtarget=x86_64-windows.win7" test

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig build "-Dtarget=aarch64-macos.11.0.0" test

