name: build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig build -Dtarget=x86_64-linux-gnu
      - run: zig build -Dtarget=aarch64-linux-gnu
      - run: zig build -Dtarget=x86_64-macos.11.0.0
      - run: zig build -Dtarget=aarch64-macos.11.0.0
      - run: zig build -Dtarget=x86_64-windows.win7
      - run: zig build -Dtarget=aarch64-windows
      - run: find zig-out

      - run: |
          curl -L https://github.com/free-audio/clap-validator/releases/download/0.3.2/clap-validator-0.3.2-ubuntu-18.04.tar.gz | tar -xz
          chmod +x clap-validator
          ./clap-validator validate zig-out/x86_64-linux-gnu/NoiseRF.clap

